import Link from "next/link";
import {
  ArrowUpRight,
  Mail,
  Clock,
  CheckCircle2,
  Circle,
  Send,
  Sparkles,
  BrainCircuit,
  AlertCircle,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/system/empty-state";
import { PageHeader } from "@/components/dashboard/page-header";
import { FollowUpsActions } from "@/components/dashboard/actions/follow-ups-actions";
import { formatRelativeTime } from "@/lib/format";
import { getSupabaseAdmin } from "@/lib/db/client";

export default async function FollowUpsPage() {
  let followUpRecords: any[] = [];

  if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY) {
    try {
      const supabase = getSupabaseAdmin();
      const { data } = await supabase
        .from("ai_follow_ups")
        .select(`
          id, title, body, rationale, status, priority,
          confidence, model_name, due_at, generated_at,
          completed_at, metadata,
          customer:customers ( id, display_name, company_name )
        `)
        .is("deleted_at", null)
        .order("generated_at", { ascending: false })
        .limit(50);

      followUpRecords = (data ?? []).map((f: any) => ({
        id: f.id,
        title: f.title,
        body: f.body,
        rationale: f.rationale,
        status: f.status,
        priority: f.priority,
        confidence: f.confidence,
        modelName: f.model_name,
        dueAt: f.due_at,
        generatedAt: f.generated_at,
        completedAt: f.completed_at,
        metadata: f.metadata,
        customerName: f.customer?.display_name ?? null,
        companyName: f.customer?.company_name ?? null,
        customerId: f.customer?.id ?? null,
      }));
    } catch {
      // fallback
    }
  }

  const pending = followUpRecords.filter((f) => f.status === "draft" || f.status === "queued");
  const sent = followUpRecords.filter((f) => f.status === "sent" || f.status === "completed");
  const cancelled = followUpRecords.filter((f) => f.status === "cancelled");

  return (
    <div className="space-y-6">
      <PageHeader
        icon={<Mail className="h-5 w-5" />}
        badge="AI-generated outreach"
        title="Follow-Ups"
        description="Memory-backed follow-up emails generated by RecallIQ. Each email is personalized using objections, tone preferences, and prior conversation context."
        helpTitle="How follow-ups work"
        helpText="After each customer conversation, RecallIQ recalls relevant memory such as objections, preferences, and tone and generates a personalized follow-up. Use this page to review drafts and confirm the AI is turning context into concrete next steps."
        actions={<FollowUpsActions />}
      />

      {/* Stats row */}
      {followUpRecords.length > 0 && (
        <div className="grid grid-cols-3 gap-4">
          <StatCard
            label="Pending"
            value={pending.length}
            icon={<Circle className="h-4 w-4 text-amber-400" />}
          />
          <StatCard
            label="Sent"
            value={sent.length}
            icon={<Send className="h-4 w-4 text-emerald-400" />}
          />
          <StatCard
            label="Cancelled"
            value={cancelled.length}
            icon={<AlertCircle className="h-4 w-4 text-slate-400" />}
          />
        </div>
      )}

      {!followUpRecords.length ? (
        <EmptyState
          actionLabel="Generate first follow-up"
          description="No follow-up emails yet. Open a customer conversation and use the AI generation tools to create memory-backed outreach."
          icon={<Mail className="h-7 w-7" />}
          title="No follow-ups generated yet"
        />
      ) : (
        <div className="space-y-6">
          {pending.length > 0 && (
            <section className="space-y-3">
              <h2 className="text-sm font-semibold flex items-center gap-2" style={{ color: "var(--text-secondary)" }}>
                <Circle className="h-4 w-4 text-amber-400" />
                Pending ({pending.length})
              </h2>
              <div className="space-y-3">
                {pending.map((fu) => <FollowUpCard key={fu.id} followUp={fu} />)}
              </div>
            </section>
          )}

          {sent.length > 0 && (
            <section className="space-y-3">
              <h2 className="text-sm font-semibold flex items-center gap-2" style={{ color: "var(--text-secondary)" }}>
                <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                Sent / Completed ({sent.length})
              </h2>
              <div className="space-y-3">
                {sent.map((fu) => <FollowUpCard key={fu.id} followUp={fu} />)}
              </div>
            </section>
          )}
        </div>
      )}
    </div>
  );
}

function StatCard({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-center gap-2 mb-2">
          {icon}
          <span className="text-xs font-medium" style={{ color: "var(--text-secondary)" }}>{label}</span>
        </div>
        <p className="text-2xl font-bold" style={{ color: "var(--text-primary)" }}>{value}</p>
      </CardContent>
    </Card>
  );
}

function FollowUpCard({ followUp }: { followUp: any }) {
  const statusVariant = {
    draft: "secondary" as const,
    queued: "warning" as const,
    sent: "success" as const,
    completed: "success" as const,
    cancelled: "destructive" as const,
  }[followUp.status as string] ?? "secondary" as const;

  const confidencePct = Math.round((followUp.confidence ?? 0) * 100);
  const confVariant = confidencePct >= 80 ? "success" as const : confidencePct >= 50 ? "warning" as const : "destructive" as const;

  const tone = (followUp.metadata as any)?.tone ?? null;

  return (
    <Card>
      <CardContent className="p-5">
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <p className="text-sm font-semibold truncate" style={{ color: "var(--text-primary)" }}>
                {followUp.title}
              </p>
              {tone && (
                <Badge variant="secondary" className="text-[10px]">{tone}</Badge>
              )}
            </div>
            {followUp.companyName && (
              <p className="text-xs mt-0.5 flex items-center gap-1" style={{ color: "var(--text-secondary)" }}>
                <BrainCircuit className="h-3 w-3" />
                {followUp.customerName} · {followUp.companyName}
              </p>
            )}
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <Badge variant={confVariant}>{confidencePct}% confidence</Badge>
            <Badge variant={statusVariant}>{followUp.status}</Badge>
          </div>
        </div>

        {/* Email body preview */}
        <div className="rounded-xl p-3 mb-3" style={{ background: "var(--bg-subtle)", border: "1px solid var(--border-subtle)" }}>
          <p className="text-xs leading-relaxed line-clamp-3" style={{ color: "var(--text-secondary)" }}>
            {followUp.body}
          </p>
        </div>

        {/* Rationale */}
        {followUp.rationale && (
          <div className="rounded-xl p-2.5 mb-3 flex gap-2" style={{ background: "var(--info-bg)", border: "1px solid var(--info-border)" }}>
            <Sparkles className="h-3.5 w-3.5 shrink-0 mt-0.5" style={{ color: "var(--info-text)" }} />
            <p className="text-xs leading-relaxed" style={{ color: "var(--text-secondary)" }}>
              <span className="font-medium" style={{ color: "var(--text-primary)" }}>Why this approach: </span>
              {followUp.rationale}
            </p>
          </div>
        )}

        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3 text-[10px]" style={{ color: "var(--text-secondary)" }}>
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {formatRelativeTime(followUp.generatedAt)}
            </span>
            {followUp.modelName && (
              <span className="font-mono">{followUp.modelName}</span>
            )}
          </div>
          {followUp.customerId && (
            <Link href={`/customers/${followUp.customerId}`}>
              <Button variant="ghost" size="sm" className="h-7 text-xs">
                View customer <ArrowUpRight className="h-3 w-3 ml-1" />
              </Button>
            </Link>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
